DELETE FROM cities WHERE (name, country) IN (
    ('Kyiv', 'Ukraine'),
    ('Lviv', 'Ukraine'),
    ('Kharkiv', 'Ukraine'),
    ('Odesa', 'Ukraine'),
    ('Dnipro', 'Ukraine'),
    ('Kherson', 'Ukraine'),
    ('Vinnytsia', 'Ukraine'),
    ('Poltava', 'Ukraine'),
    ('Ivano-Frankivsk', 'Ukraine'),
    ('Chernihiv', 'Ukraine'),
    ('Warsaw', 'Poland'),
    ('Berlin', 'Germany'),
    ('Paris', 'France'),
    ('Rome', 'Italy'),
    ('Madrid', 'Spain'),
    ('London', 'United Kingdom'),
    ('Vienna', 'Austria'),
    ('Prague', 'Czech Republic'),
    ('Amsterdam', 'Netherlands'),
    ('Stockholm', 'Sweden'),
    ('Brussels', 'Belgium'),
    ('Lisbon', 'Portugal'),
    ('Athens', 'Greece'),
    ('Oslo', 'Norway'),
    ('Helsinki', 'Finland'),
    ('Copenhagen', 'Denmark'),
    ('Budapest', 'Hungary'),
    ('Zagreb', 'Croatia'),
    ('Bucharest', 'Romania'),
    ('Belgrade', 'Serbia'),
    ('Ljubljana', 'Slovenia'),
    ('Sofia', 'Bulgaria')
);
