services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DSN=root:1111@tcp(db:3306)/weather_service?parseTime=true
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: weather_service
    # ports:
      # - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
