services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - db
    env_file:
    - .env
    entrypoint: [
      "migrate",
      "-path=/migrations",
      "-database=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DB}?parseTime=true"
    ]


volumes:
  db_data: